#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': "OpenMDAO interface to CD-adapco's STAR-CCM+, CFD Simulation Software",
 'download_url': '',
 'entry_points': '[openmdao.component]\nStarCCM.StarCCM.StarCCM_wrapper=StarCCM.StarCCM:StarCCM_wrapper\n\n[openmdao.container]\nStarCCM.StarCCM.StarCCM_wrapper=StarCCM.StarCCM:StarCCM_wrapper',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao, Star-CCM+, CFD, volume mesh'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'StarCCM',
 'package_data': {'StarCCM': []},
 'package_dir': {'': 'src'},
 'packages': ['StarCCM', 'StarCCM.test'],
 'url': '',
 'version': '0.0.1',
 'zip_safe': False}


setup(**kwargs)

